### ISSUE TITLE
Napisanie kodu HTML na paski doświadczenia.

### ISSUE THREAD

**Issue by Wilczur2142** [Wilczur2142/krzysztofgepard.me#1]

**Comment by Szmyk** [comment]
Nie da się :D

**Comment by Szmyk** [comment]
Nie no, może być tak jak na mojej stronie? http://szymonzak.pl

**Comment by Wilczur2142** [comment]
No myślałem dokładnie o czymś takim albo jeszcze w formie kółka.

**Comment by Szmyk** [comment]
Gotowe!
